### ISSUE TITLE
인터페이스와 상속의 차이?

### ISSUE THREAD

**Issue by Tentennball** [WooJJam/this-is-java-study#4]
## ❓인터페이스와 추상클래스의 차이
- 인터페이스와 추상 클래스 모두 오버라이딩을 통해서 구현하는데 차이가 무엇일까요?
[직접 작성한 velog 보기](https://velog.io/@lth8905/%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4%EC%99%80-%EC%B6%94%EC%83%81%ED%81%B4%EB%9E%98%EC%8A%A4%EC%9D%98-%EC%B0%A8%EC%9D%B4)

**Comment by Tentennball** [comment]
https://velog.io/@lth8905/%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4%EC%99%80-%EC%B6%94%EC%83%81%ED%81%B4%EB%9E%98%EC%8A%A4%EC%9D%98-%EC%B0%A8%EC%9D%B4

**Comment by WooJJam** [comment]
잘 읽었습니다~

해당 이슈는 PR Development를 통해 Close 하겠습니다.
